from .prompts import (
    TUTOR_MAP, TUTOR_STRICT, TUTOR_NEURIPS, TUTOR_NATURE,
    POLISH_REMOVE_AI_TONE, POLISH_ACADEMIC,
    INNOVATION_CHECK, REBUTTAL_GENERATE,
    RESEARCH_ANALYZE, CITATION_BUILD, BLUEPRINT_BUILD,
    CN_TEMPLATES, PAPER_DECONSTRUCT,
)
